#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: Aluisio Martins Junior <junior@mjpsolucoes.com.br>
 * Date: 19/04/2017
 * Time: 06:45
 */

include 'vendor/autoload.php';

use GuzzleHttp\Client;

define('DS', DIRECTORY_SEPARATOR);

$pathFunctions = str_replace('_', DS, 'core_Utils_functions.php');

include $pathFunctions;

// Iniciamos o "contador"
$timeStart = microtimeFloat();

// Iniciamos o "contador"
$timeStart = microtimeFloat();

$path = isset($argv[1]) ? $argv[1] : '';

if (empty($path)) {
    echo messageBuilder('Defina um diretorio!', 1, 1);
    exit;
}

if (is_dir($path)) {
    echo messageBuilder('O diretorio selecionado ja existe!', 1, 1);
    exit;
}

if (!is_dir($path)) {
    mkdir($path);
    
    if (!class_exists('ZipArchive')) {
        throw new RuntimeException('The Zip PHP extension is not installed. Please install it and try again.');
    }
    
    //$output = shell_exec('cd ' . $path);
    //echo "$output";
    
    //$output = shell_exec('git clone https://github.com/junioraluisio/painless.git');
    //echo "$output";
    
    $zipFile = makeFilename();
    
    $guzzleClient = new Client(['curl' => [CURLOPT_SSL_VERIFYPEER => false,],]);
    
    $response = $guzzleClient->get('https://github.com/junioraluisio/painless/archive/master.zip');
    
    file_put_contents($zipFile, $response->getBody());
    
    extractZip($zipFile, __DIR__,$path);
    
    cleanUp($zipFile);
    
    echo messageBuilder('Instalado com sucesso em "' . $path . '"!', 1, 1);
}

// Terminamos o "contador" e exibimos
$timeEnd = microtimeFloat();

// Exibimos uma mensagem
echo messageBuilderTime($timeStart, $timeEnd);

