#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: Junior
 * Date: 16/04/2017
 * Time: 08:10
 */

define('DS', DIRECTORY_SEPARATOR);

$pathFunctions = str_replace('_',DS,'core_Utils_functions.php');

include $pathFunctions;

// Iniciamos o "contador"
$timeStart = microtimeFloat();

$dirFontCore   = __DIR__ . DS . 'core';
$dirFontVendor = __DIR__ . DS . 'vendor';

// Iniciamos o "contador"
$timeStart = microtimeFloat();

$path = isset($argv[1]) ? $argv[1] : '';

if (empty($path)) {
    echo messageBuilder('Defina um diretorio!', 1, 1);
    exit;
}

if (is_dir($path)) {
    //echo messageBuilder('O diretorio selecionado ja existe!', 1, 1);
    //exit;
}

if (!is_dir($path)) {
    mkdir($path);
    
    // Copy "core"
    copyDirectory($dirFontCore, $path . DS . 'core');
    
    // Copy "vendor"
    copyDirectory($dirFontVendor, $path . DS . 'vendor');
    
    copyArchives(__DIR__, $path);
    
    echo messageBuilder('Instalado com sucesso em "' . $path . '"!', 1, 1);
}

// Terminamos o "contador" e exibimos
$timeEnd = microtimeFloat();

// Exibimos uma mensagem
echo messageBuilderTime($timeStart, $timeEnd);

