#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: Aluisio Martins Junior <junior@mjpsolucoes.com.br>
 * Date: 19/04/2017
 * Time: 06:45
 */

include 'vendor/autoload.php';

use GuzzleHttp\Client;

define('DS', DIRECTORY_SEPARATOR);

include 'core/Utils/functions.php';

// Iniciamos o "contador"
$timeStart = microtimeFloat();

$path = isset($argv[1]) ? $argv[1] : '';

if (empty($path)) {
    echo messageBuilder('Define a directory!', 1, 1);
    exit;
}

if (is_dir($path)) {
    echo messageBuilder('The selected directory already exists!', 1, 1);
} else {
    mkdir($path);
    mkdir($path . DS . 'temp');
    
    if (!class_exists('ZipArchive')) {
        echo messageBuilder('The Zip PHP extension is not installed. Please install it and try again.', 1, 1);
    }
    
    $zipFile = makeFilename($path);
    
    $guzzleClient = new Client(['curl' => [CURLOPT_SSL_VERIFYPEER => false,],]);
    
    $urlGitHub = 'https://github.com/junioraluisio/painless-invoker/archive/master.zip';
    
    $response = $guzzleClient->get($urlGitHub);
    
    file_put_contents($zipFile, $response->getBody());
    
    extractZip($zipFile, $path, $path);
    
    cleanUp($zipFile);
    
    echo messageBuilder('Successfully installed in "' . $path . '"!', 1, 1);
}

// Terminamos o "contador" e exibimos
$timeEnd = microtimeFloat();

// Exibimos uma mensagem
echo messageBuilderTime($timeStart, $timeEnd);

